### ISSUE TITLE
[Feature Request] Add support for GTK4 titlebar

### ISSUE THREAD

**Issue by julianfairfax** [minetest/irrlicht#186]
It seems Minetest is based on this engine. When installing Minetest on a Linux system, or at least, a GNOME system, it has a GTK3 titlebar. It would be nice if support could be added for a GTK4 titlebar, as that's the new standard on GNOME systems.

**Comment by Desour** [comment]
We are planning to switch to SDL2. Please try compiling with `-DUSE_SDL2`. If the issue consists, it's an upstream issue I think (SDL probably sets the window decorations).

**Comment by Desour** [comment]
Are you sure you have SDL2 installed? In arch linux at least, `SDL2Config.cmake` is provided by the package.

**Comment by numberZero** [comment]
Window frame is rendered by the window manager, not by the app.

Oh wait, that’s GNOME. Still, the frame you see is likely rendered by the window manager; I doubt SDL links to GTK just to render the titlebar.

**Comment by numberZero** [comment]
> I doubt SDL links to GTK just to render the titlebar.

Correction: it may link to [libdecor](https://gitlab.freedesktop.org/libdecor/libdecor) which may in fact load GTK for that.

So, try running Minetest with the `SDL_VIDEO_WAYLAND_ALLOW_LIBDECOR` environment variable set to `0` to disable libdecor. If that fixes the problem, report it to libdecor (in fact, if their README is up to date, they only support GTK3 currently). Otherwise, report it to GNOME shell.

**Comment by numberZero** [comment]
> It probably is in fact a libdecor limitation then.

While `libdecor` likely has that limitation your testing suggests that GNOME shell *also* has that limitation, i.e. for whatever reason, it only provides GTK3 titlebars for non-GTK windows.
