### ISSUE TITLE
Readd all media formats

### ISSUE THREAD

**Issue by appgurueu** [minetest/irrlicht#65]
They shouldn't have been removed in the first place; their removal breaks Minetest's backwards compatibility. Keeping the readers around is not too much of a hassle in terms of added compile time and code base size.

**Comment by sfan5** [comment]
Adding "all" formats back does not make in the first place because that would include PVR, DDS, HalfLife (whatever that is) and LMP which Minetest has never allowed the use of.

For the rest (TGA, PSD, PCX, WAL, PPM, RGB) ask yourself this:
* Which programs can write this format today?
* Can Irrlicht even read a file exported today? (<- PSD?)
* Is the format primitive (e.g. no compression support)? In which case there is either no reason to use it (for existing media) *or* BMP is a suitable alternative (for dynamic generation).
* Does this format have any use in mods/games we know of?

**Comment by appgurueu** [comment]
I mostly want MD2, because it offers features B3D and X do not have.

**Comment by sfan5** [comment]
What are those features? Animations?

**Comment by appgurueu** [comment]
> What are those features? Animations?

Yes

**Comment by sfan5** [comment]
B3D and X both(?) do that too so there must be another reason why you prefer MD2...

**Comment by appgurueu** [comment]
> B3D and X both(?) do that too so there must be another reason why you prefer MD2...

Well, MD2 animations are a different breed. Not to mention that I don't trust B3D and X animations...

**Comment by wsor4035** [comment]
MD2: https://github.com/minetest/irrlicht/pull/48#issuecomment-919343927
